services:  
  core:
    build: core
    volumes:
      - ./images/php:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
      - cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: N6K1SFO4S73CT0N4
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    networks:
      - frontend
      - backend

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: WAjcy0kuV4GVTW7Ditzn
      MYSQL_DATABASE: solidarity_core
      MYSQL_USER: solidarity
      MYSQL_PASSWORD: WAjcy0kuV4GVTW7Ditzn

  frontend:
    build: front-end
    ports:
      - '8100:8100'
    volumes:
      - .:/opt/solidarity
      - /opt/solidarity/node_modules
    command: ionic serve --all
    depends_on:
      - frontend-nginx
    networks:
      - frontend

  
  frontend-nginx:
    build: docker/frontend-nginx
    ports:
        - 8080:8080
    networks:
      - frontend
    restart: always

  php-nginx:
    build: docker/php-nginx
    ports:
        - 8081:8081
    networks:
      - backend
    restart: always

  cache:
    image: memcached:1.6-alpine

networks:
  frontend:
  backend: